name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  filename:  # path to of file
    required: true
  content:  # Content of file
    description: ' Content of file'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
